# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: send love message
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Ò good job broo 😍
          At [${{ github.workspace }}](https://github.com/${{ github.workspace }})
          On branch `${{ github.ref }}`
          SHA: `${{ github.sha }}`
        photo: https://tenor.com/view/camlansuc-cls-kisses-flying-kiss-smile-gif-13263229

    - name: send bruh message
      if: failed()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Bruh what have u doneeee?
          At [${{ github.workspace }}](https://github.com/${{ github.workspace }})
          On branch `${{ github.ref }}`
          SHA: `${{ github.sha }}`
        photo: https://tenor.com/view/camlansuc-12345-cls-linda-count-gif-13238517

      env:
        CI: true
